import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import boundaries from 'eslint-plugin-boundaries';
import globals from 'globals';

// Public entry points (the bare specifiers below) are the ONLY allowed import
// shape for these packages. Any path-suffixed import is internal-reach and is
// rejected by no-restricted-imports below.
//   @sovereignclaw/core
//   @sovereignclaw/memory
//   @sovereignclaw/mesh
//   @sovereignclaw/inft
//   @sovereignclaw/reflection
const FORBIDDEN_DEEP_IMPORT_PATTERNS = [
  // Any path-suffixed import into a SovereignClaw package is internal-reach.
  // Public entries are above; anything beyond the package root is forbidden.
  '@sovereignclaw/*/dist/**',
  '@sovereignclaw/*/dist',
  '@sovereignclaw/*/src/**',
  '@sovereignclaw/*/src',
  '@sovereignclaw/*/internal/**',
  '@sovereignclaw/*/internal',
  '@sovereignclaw/*/lib/**',
  '@sovereignclaw/*/lib',
  '@sovereignclaw/**/dist/**',
  '@sovereignclaw/**/src/**',
  '@sovereignclaw/**/internal/**',
];

export default tseslint.config(
  // Files to ignore entirely.
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      'contracts/lib/**',
      'contracts/out/**',
      'contracts/cache/**',
      'contracts/broadcast/**',
      // Disabled examples are documentation, not code; they intentionally
      // demonstrate violations and must NOT be linted.
      'examples/lint-violations/**',
      // Generated by Next; should not be edited.
      'apps/web/next-env.d.ts',
    ],
  },

  // Base JS recommended.
  js.configs.recommended,

  // TypeScript recommended (non-type-checked — keeps lint fast).
  ...tseslint.configs.recommended,

  // Project-wide rules + the no-internal-reach guard.
  {
    files: ['**/*.{ts,tsx,js,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser },
    },
    plugins: {
      boundaries,
    },
    settings: {
      // Treat every workspace package as its own boundary "element".
      'boundaries/elements': [
        { type: 'agents', pattern: 'agents/**' },
        { type: 'orchestrator', pattern: 'apps/orchestrator/**' },
        { type: 'web', pattern: 'apps/web/**' },
        { type: 'scripts', pattern: 'scripts/**' },
        { type: 'lib', pattern: 'lib/**' },
      ],
      'boundaries/include': ['agents/**', 'apps/**', 'scripts/**', 'lib/**'],
    },
    rules: {
      // Hard-fail on any deep import into a @sovereignclaw/* package.
      // Public entry points (resolved via the bare specifier) are NOT matched
      // by these patterns and remain allowed.
      'no-restricted-imports': [
        'error',
        {
          patterns: FORBIDDEN_DEEP_IMPORT_PATTERNS.map((pattern) => ({
            group: [pattern],
            message:
              'Internal-reach into @sovereignclaw/* is forbidden (see IncomeClaw-Roadmap.md §13 #1). ' +
              'Import only from the package public entry, e.g. `@sovereignclaw/core`. ' +
              'If a needed API is missing, file an upstream PR — do not reach into internals.',
          })),
        },
      ],
      // boundaries plugin: disallow cross-element imports we don't whitelist.
      'boundaries/element-types': [
        'error',
        {
          default: 'allow',
          rules: [
            // The orchestrator and web app may consume agents and lib.
            { from: 'orchestrator', allow: ['agents', 'lib', 'orchestrator'] },
            { from: 'web', allow: ['lib', 'web'] },
            // Agents must NOT depend on the orchestrator or web — keeps agent
            // code framework-pure and reusable.
            { from: 'agents', allow: ['agents', 'lib'] },
            // Scripts (smoke tests, deploys) may use everything.
            { from: 'scripts', allow: ['lib', 'agents', 'scripts'] },
            // lib/ is leaf — no IncomeClaw-internal cross-imports.
            { from: 'lib', allow: ['lib'] },
          ],
        },
      ],
      // Tighten a few TS rules to match SovereignClaw conventions.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // Repo-root scripts & top-level config files allow console.log freely
  // (they're CLI utilities; structured logging is enforced inside apps/).
  {
    files: ['scripts/**/*.{ts,mjs,cjs,js}', '*.{js,mjs,cjs,ts}'],
    rules: { 'no-console': 'off' },
  },

  // Test files: relax a few rules.
  {
    files: ['**/*.{test,spec}.{ts,tsx}', '**/test/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-console': 'off',
    },
  },
);
